Documentation/100 vignette bmmformula
venpopov/bmm pull request #175
Opened 2024-03-23 19:45 UTC by GidonFrischkorn

#### Summary
- Add vignette for `bmmformula`

#### Tests

[x] Confirm that all tests passed
[x] Confirm that devtools::check() produces no errors

#### Release notes

2024-03-23 19:46 UTC, GidonFrischkorn commented
This is a first but pretty comprehensive draft. I wanted to share this and ask you for comments. So, feel free to comment and make edits as you see fit.

2024-03-23 19:56 UTC, venpopov commented
> This is a first but pretty comprehensive draft. I wanted to share this and ask you for comments. So, feel free to comment and make edits as you see fit.

It looks great! Thanks for putting this together.

The one suggestion I have is to skip the section "Using constant priors". I think it only adds unnecessary complexity without offering any additional features.

In it the call to default prior should be default_prior(my_formula, my_data, my_model), but if you remove the section that doesn't matter.

2024-03-23 19:57 UTC, venpopov commented on vignettes/bmmformula.Rmd
> +## Using `constant` priors
as I noted in the PR reply, I think this should be removed

2024-03-23 19:58 UTC, venpopov commented on vignettes/bmmformula.Rmd
> +## Inside the `bmmformula`
if you remove the constant priors section, just remove this subheading

2024-03-23 20:00 UTC, venpopov commented on vignettes/bmmformula.Rmd
> +## Seperating response variables from model parameters
make heading 1st level

2024-03-23 20:02 UTC, venpopov commented on vignettes/bmmformula.Rmd
> +bmmfit <- bmm:::bmmfit_mixture2p_vignette
if you keep this hidden, I suggest you include the code to fit the model from the other vignette. Right now someone might wonder where this bmmfit came from and be confused about where to extract the info from

2024-03-23 20:04 UTC, venpopov commented on vignettes/bmmformula.Rmd
> +Likewise users can call a `brms` summary instead of a `bmm` summary by setting the `backend` option in the summary function to `brms`. This way the summary function for `brmsfit` objects will be used
Add sentence for context: "bmm model use a custom summary function to format the output. You can call a ...."

2024-03-23 20:05 UTC, venpopov requested changes
I left a few specific comments, but overall it lookgs great. An overall comment is inconsistent use of second and third person language - "you can" vs "users can" vs "we can access". I suggest sticking with either you or we, and avoid the third person.

2024-03-23 20:21 UTC, venpopov commented
Another useful thing to add would be that people can choose to estimate some of the parameters that are fixed by default

2024-03-24 19:58 UTC, GidonFrischkorn commented
I have included your comments and also added a section on estimating internally fixed parameters. I added some information there how to access model parameters and distinguish parameters fixed for identification purposes from fixed parmaeters that can be estimated if needed.

Feel free to add further comments, and I hope that I managed to consistently use "you" in this version of the vignette.

2024-03-24 23:12 UTC, venpopov approved these changes

2024-03-24 23:13 UTC, venpopov commented
A few minor edits from my side, and fixed some code I noticed from the summaries in the vignettes. Good to go

2024-03-25 00:33 UTC, venpopov commented
The failed checks seem like they have nothing to do with us. I looked into it, and apparently this can happen when a dependency is updated on CRAN and it takes a few days to stabilize... https://stackoverflow.com/questions/51453717/issue-with-r-package-check-on-windows-package-suggested-but-not-available-str

2024-03-25 07:16 UTC, merged